"""RinkX command line.

rinkx run --out DIR [--no-push]      pull store, run stages, publish bundle to DIR, push store
rinkx dev-setup [--passphrase P]     create local dev keys + keyfile under .rinkx/
rinkx keyfile --out PATH             wrap a DATA_KEY with your passphrase (interactive)
rinkx store-list                     list stored versions
rinkx store-drill                    restore drill: the oldest kept version must decrypt, check and migrate
rinkx store-restore --version NAME --yes   make an older version current again (uploaded as a new version)
rinkx watchdog                       alert if the pipeline hasn't succeeded recently (watchdog.yml)
"""

from __future__ import annotations

import argparse
import getpass
import json
import logging
import os
import sys
from pathlib import Path

from rinkx import crypto
from rinkx.config import REPO_ROOT, ConfigError, Settings
from rinkx.pipeline import run
from rinkx.store import remote
from rinkx.timeutil import utcnow

DEV_ENV = REPO_ROOT / ".rinkx/dev.env"
MIN_PASSPHRASE_CHARS = 20


def load_dev_env() -> None:
    """Load .rinkx/dev.env for local dev without overriding real environment variables."""
    if os.environ.get("RINKX_ENV", "dev") != "dev" or not DEV_ENV.is_file():
        return
    for line in DEV_ENV.read_text().splitlines():
        if "=" in line and not line.lstrip().startswith("#"):
            k, v = line.split("=", 1)
            os.environ.setdefault(k.strip(), v.strip())


def check_passphrase(p: str) -> None:
    if len(p) < MIN_PASSPHRASE_CHARS:
        raise SystemExit(
            f"Passphrase too short ({len(p)} chars). Use at least {MIN_PASSPHRASE_CHARS} characters, "
            "e.g. five or more random words. The keyfile is public, so a weak passphrase can be guessed offline."
        )


def cmd_run(args: argparse.Namespace) -> int:
    settings = Settings.from_env()
    result = run(settings, Path(args.out), push=not args.no_push)
    m = result.manifest
    print(
        json.dumps(
            {
                "env": m.env,
                "configured": m.configured,
                "missing_setup": m.missing_setup,
                "files": sorted(m.files),
                "store_pulled": result.store_pulled,
                "store_pushed": result.store_pushed,
            },
            indent=2,
        )
    )
    return 0


def cmd_dev_setup(args: argparse.Namespace) -> int:
    if DEV_ENV.exists() and not args.force:
        print(f"{DEV_ENV} already exists (use --force to regenerate; this orphans the local dev store)")
        return 1
    data_key, store_key = crypto.new_key(), crypto.new_key()
    DEV_ENV.parent.mkdir(parents=True, exist_ok=True)
    DEV_ENV.write_text(
        "# Local development keys. Never commit. Generated by `rinkx dev-setup`.\n"
        "RINKX_ENV=dev\n"
        f"RINKX_DATA_KEY={crypto.b64e(data_key)}\n"
        f"RINKX_STORE_KEY={crypto.b64e(store_key)}\n"
    )
    DEV_ENV.chmod(0o600)
    keyfile = crypto.make_keyfile(args.passphrase, data_key)
    (REPO_ROOT / ".rinkx/keyfile.json").write_text(json.dumps(keyfile, indent=2))
    print(f"Wrote {DEV_ENV} and .rinkx/keyfile.json (dev passphrase: {args.passphrase!r})")
    return 0


def cmd_keyfile(args: argparse.Namespace) -> int:
    raw = os.environ.get("RINKX_DATA_KEY")
    if raw:
        data_key = crypto.b64d(raw)
        print("Using DATA_KEY from RINKX_DATA_KEY.")
    else:
        data_key = crypto.new_key()
        print("Generated a new DATA_KEY. Save it as the Actions secret DATA_KEY:\n")
        print(f"  {crypto.b64e(data_key)}\n")
    p1 = getpass.getpass("Passphrase: ")
    check_passphrase(p1)
    if getpass.getpass("Repeat passphrase: ") != p1:
        raise SystemExit("Passphrases differ.")
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(crypto.make_keyfile(p1, data_key), indent=2) + "\n")
    print(f"Wrote {out}. Commit it; it is safe to publish (it only works with your passphrase).")
    return 0


def cmd_store_list(_: argparse.Namespace) -> int:
    for name in remote.backend_for(Settings.from_env()).list_assets():
        print(name)
    return 0


def cmd_store_drill(_: argparse.Namespace) -> int:
    settings = Settings.from_env()
    settings.workdir.mkdir(parents=True, exist_ok=True)
    r = remote.drill(
        remote.backend_for(settings), settings.require_store_key(), settings.workdir, settings.db_dir, utcnow()
    )
    # Names, ages and row counts only: nothing from inside the store is printed.
    print(json.dumps({"ok": r.ok, "version": r.version, "age_days": r.age_days, **r.detail}, indent=2))
    return 0 if r.ok else 1


def cmd_store_restore(args: argparse.Namespace) -> int:
    if not args.yes:
        print("Restoring makes an older version current. Re-run with --yes to confirm.")
        return 1
    settings = Settings.from_env()
    settings.workdir.mkdir(parents=True, exist_ok=True)
    name = remote.restore(remote.backend_for(settings), settings.require_store_key(), args.version, settings.workdir)
    print(f"Restored {args.version}; it is now the current store as {name}.")
    return 0


def cmd_watchdog(_: argparse.Namespace) -> int:
    from rinkx import watchdog

    return watchdog.main(Settings.from_env())


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    load_dev_env()
    parser = argparse.ArgumentParser(prog="rinkx")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("run", help="run the pipeline and publish the bundle")
    p.add_argument("--out", required=True, help="output directory for the data bundle (e.g. web/dist/data)")
    p.add_argument("--no-push", action="store_true", help="do not upload the updated store")
    p.set_defaults(func=cmd_run)

    p = sub.add_parser("dev-setup", help="create local dev keys and keyfile")
    p.add_argument("--passphrase", default="rinkx-local-dev-passphrase")
    p.add_argument("--force", action="store_true")
    p.set_defaults(func=cmd_dev_setup)

    p = sub.add_parser("keyfile", help="create keyfile.json from DATA_KEY and your passphrase")
    p.add_argument("--out", default=str(REPO_ROOT / "config/keyfile.json"))
    p.set_defaults(func=cmd_keyfile)

    p = sub.add_parser("store-list", help="list stored store versions")
    p.set_defaults(func=cmd_store_list)

    p = sub.add_parser("store-drill", help="check that the oldest kept version still restores (read-only)")
    p.set_defaults(func=cmd_store_drill)

    p = sub.add_parser("store-restore", help="make an older stored version the current one")
    p.add_argument("--version", required=True, help="asset name from store-list, e.g. rinkx-20261001T...Z.db.enc")
    p.add_argument("--yes", action="store_true", help="confirm")
    p.set_defaults(func=cmd_store_restore)

    p = sub.add_parser("watchdog", help="alert when the pipeline hasn't succeeded recently")
    p.set_defaults(func=cmd_watchdog)

    args = parser.parse_args(argv)
    try:
        return int(args.func(args))
    except ConfigError as exc:
        print(f"configuration error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
